# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/skytthe/RobWork/trunk/RobWorkStudio/projects/Rob2_project3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/skytthe/RobWork/trunk/RobWorkStudio/projects/Rob2_project3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skytthe/RobWork/trunk/RobWorkStudio/projects/Rob2_project3/CMakeFiles /home/skytthe/RobWork/trunk/RobWorkStudio/projects/Rob2_project3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skytthe/RobWork/trunk/RobWorkStudio/projects/Rob2_project3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rob2_project3

# Build rule for target.
rob2_project3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rob2_project3
.PHONY : rob2_project3

# fast build rule for target.
rob2_project3/fast:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/build
.PHONY : rob2_project3/fast

moc_rob2_project3.o: moc_rob2_project3.cxx.o
.PHONY : moc_rob2_project3.o

# target to build an object file
moc_rob2_project3.cxx.o:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/moc_rob2_project3.cxx.o
.PHONY : moc_rob2_project3.cxx.o

moc_rob2_project3.i: moc_rob2_project3.cxx.i
.PHONY : moc_rob2_project3.i

# target to preprocess a source file
moc_rob2_project3.cxx.i:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/moc_rob2_project3.cxx.i
.PHONY : moc_rob2_project3.cxx.i

moc_rob2_project3.s: moc_rob2_project3.cxx.s
.PHONY : moc_rob2_project3.s

# target to generate assembly for a file
moc_rob2_project3.cxx.s:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/moc_rob2_project3.cxx.s
.PHONY : moc_rob2_project3.cxx.s

qrc_resources.o: qrc_resources.cxx.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cxx.o:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/qrc_resources.cxx.o
.PHONY : qrc_resources.cxx.o

qrc_resources.i: qrc_resources.cxx.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cxx.i:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/qrc_resources.cxx.i
.PHONY : qrc_resources.cxx.i

qrc_resources.s: qrc_resources.cxx.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cxx.s:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/qrc_resources.cxx.s
.PHONY : qrc_resources.cxx.s

rob2_project3.o: rob2_project3.cpp.o
.PHONY : rob2_project3.o

# target to build an object file
rob2_project3.cpp.o:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/rob2_project3.cpp.o
.PHONY : rob2_project3.cpp.o

rob2_project3.i: rob2_project3.cpp.i
.PHONY : rob2_project3.i

# target to preprocess a source file
rob2_project3.cpp.i:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/rob2_project3.cpp.i
.PHONY : rob2_project3.cpp.i

rob2_project3.s: rob2_project3.cpp.s
.PHONY : rob2_project3.s

# target to generate assembly for a file
rob2_project3.cpp.s:
	$(MAKE) -f CMakeFiles/rob2_project3.dir/build.make CMakeFiles/rob2_project3.dir/rob2_project3.cpp.s
.PHONY : rob2_project3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rob2_project3"
	@echo "... moc_rob2_project3.o"
	@echo "... moc_rob2_project3.i"
	@echo "... moc_rob2_project3.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
	@echo "... rob2_project3.o"
	@echo "... rob2_project3.i"
	@echo "... rob2_project3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

